### ISSUE TITLE
How to control MAX2870 in my computer

### ISSUE THREAD

**Issue by ming020617** [brycecherry75/MAX2870#7]
hi,brycecherry.I'm a newly enrolled PhD student at the University of Science and Technology of China.Recently we had to make a prototype and my mentor asked me to solve the signal source, so I bought the development board MAX2870. But I don't really know how to subsequently control it through a computer program. For example, controlling its output frequency and scanning step etc. What software do I need to download and whether to program it in C or python? I look forward to your reply and send my most sincere thanks!

**Comment by brycecherry75** [comment]
It is written in C for the Arduino IDE.
